#!/usr/bin/env bash
set -e

echo "Automatically converting Nipype tasks to Pydra tasks..."

conv_dir=$(dirname $0)

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Stashing current changes to '$CURRENT_BRANCH'..."
git stash -m "pre-auto-conv" || true

echo "Switching to 'auto-conv' branch..."
git checkout auto-conv

echo "Running nipype2pydra conversion..."
nipype2pydra convert $conv_dir/specs $conv_dir/..

echo "Committing converted tasks..."
git add pydra/tasks/ants
git commit -m "Auto-converted Nipype tasks to Pydra tasks"

echo "Rebasing '$CURRENT_BRANCH' to apply changes..."
git checkout $CURRENT_BRANCH
git rebase auto-conv

echo "Popping stashed changes..."
git stash pop || echo "No stashed changes to pop."

echo "Successfully converted Nipype tasks to Pydra tasks and rebased '$CURRENT_BRANCH' on top of auto-conv changes."
